export const UPDATE_EXERCISE = "UPDATE_EXERCISE";

export const ADD_TO_ROUTINE = "ADD_TO_ROUTINE";
export const ADD_MULTIPLE_TO_ROUTINE = "ADD_MULTIPLE_TO_ROUTINE";
export const REMOVE_FROM_ROUTINE = "REMOVE_FROM_ROUTINE";
export const CLEAR_ROUTINE = "CLEAR_ROUTINE";
export const UPDATE_SETS = "UPDATE_SETS";
export const UPDATE_REPS = "UPDATE_REPS";
export const UPDATE_WEIGHT = "UPDATE_WEIGHT";
export const TOGGLE_ROUTINE = "TOGGLE_ROUTINE";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
